import { randomElement } from '../../../tools/helpers';

const excuses = [
  'studying',
  'baking cookies',
  'looking for keys',
  'charging airpods',
  'making a sandwich',
  'integrating',
  'differentiating',
  'taking a nap',
  'reading',
  'working out',
  'titrating',
  'getting lunch',
  'getting dinner',
  'procrastinating',
  'not paying attention',
  '"studying"',
  'browsing amazon',
  'tweeting',
  'talking to mom',
  'white water rafting',
  'practicing piano',
  'climbing rocks',
  'tenting',
  'bowling',
  'certainly not texting and driving',
  'updating apps',
  'unsubscribing from newsletters',
  'waiting for pasta',
  'waiting for the c3',
  '3d printing',
  'listening to a podcast',
  'stuck on a 30s ad',
  'making flashcards',
  'doing math hw',
  'doing apts',
  'lost in perkins',
  'getting 8 hrs of sleep',
  'still at marketplace',
  'calling an uber',
  'sending venmo requests',
  'completing two-step verification',
  'dropping a class',
  'searching for classes',
  'considering a new major',
  'reloading flex',
  'sending streaks',
  'watching netflix',
  'skipping an 8:30',
  'doing laundry',
  'browsing tinder',
  'burning benches',
  'still in a lab',
  'taking a midterm',
  'late again',
  'writing the questions',
  'readying cannons',
  'counting down',
  'entering warp drive',
  'starting your engines',
  'brushing off cobwebs',
  'ordering pizza',
  'learning spanish',
  'learning french',
  'learning chinese',
  'learning japanese',
  'learning german',
  'learning sign language',
  'hacking into the system',
  'writing an essay',
  'coding',
  'playing fortnite',
  'eating pi',
  'waiting for brian',
  'googling answers',
  'applying filters',
  'doing a barrel roll',
  'making toast',
  'mining cryptocurrency',
  'definitly not crashing the site',
];

export default () => {
  return randomElement(excuses);
}
